# The config of the 3x10-30 CoordSum environment
name: CoordSum
task_name: 3x10-30-v0

task_config:
  num_agents: 3
  num_actions: 10

env_kwargs:
  {}  # there are no scenario specific env_kwargs for this env