# The config of the 8x8-2p-2f-coop scenario with the VectorObserver set as default
name: LevelBasedForaging-v0
task_name: 8x8-2p-2f-coop

task_config:
  grid_size: 8
  fov: 8
  num_agents: 2
  num_food: 2
  max_agent_level: 2
  force_coop: True

env_kwargs:
  {}  # there are no scenario specific env_kwargs for this env
