# The config of the medium-6ag environment
name: RobotWarehouse-v0
task_name: medium-6ag

task_config:
  column_height: 8
  shelf_rows: 2
  shelf_columns: 5
  num_agents: 6
  sensor_range: 1
  request_queue_size: 6

env_kwargs:
  {}  # there are no scenario specific env_kwargs for this env
