# The config of the tiny-2ag environment
name: RobotWarehouse-v0
task_name: tiny-2ag

task_config:
  column_height: 8
  shelf_rows: 1
  shelf_columns: 3
  num_agents: 2
  sensor_range: 1
  request_queue_size: 2

env_kwargs:
  {}  # there are no scenario specific env_kwargs for this env
