# The config of the tiny-4ag-easy environment
name: RobotWarehouse-v0
task_name: tiny-4ag-easy

task_config:
  column_height: 8
  shelf_rows: 1
  shelf_columns: 3
  num_agents: 4
  sensor_range: 1
  request_queue_size: 8

env_kwargs:
  {}  # there are no scenario specific env_kwargs for this env
