# The config of the large-4ag environment
name: RobotWarehouse-v0
task_name: xlarge-4ag

task_config:
  column_height: 8
  shelf_rows: 4
  shelf_columns: 5
  num_agents: 4
  sensor_range: 1
  request_queue_size: 4

env_kwargs:
  {}  # there are no scenario specific env_kwargs for this env
