# ---CNN Networks---
actor_network:
  pre_torso:
    _target_: mava.networks.torsos.CNNTorso
    channel_sizes: [32, 32]
    kernel_sizes: [3, 3]
    strides: [1, 1]
    use_layer_norm: False
    activation: relu

critic_network:
  pre_torso:
    _target_: mava.networks.torsos.CNNTorso
    channel_sizes: [32, 32]
    kernel_sizes: [3, 3]
    strides: [1, 1]
    use_layer_norm: False
    activation: relu
