# ---MLP Networks---
actor_network:
  pre_torso:
    _target_: mava.networks.torsos.MLPTorso
    layer_sizes: [128, 128]
    use_layer_norm: False
    activation: relu

critic_network:
  pre_torso:
    _target_: mava.networks.torsos.MLPTorso
    layer_sizes: [128, 128]
    use_layer_norm: False
    activation: relu
