# ---Recurrent Structure Networks---
hidden_state_dim: 128 # The size of the RNN hiddenstate for each agent.

actor_network:
  pre_torso:
    _target_: mava.networks.torsos.MLPTorso
    layer_sizes: [128]
    use_layer_norm: False
    activation: relu
  post_torso:
    _target_: mava.networks.torsos.MLPTorso
    layer_sizes: [128]
    use_layer_norm: False
    activation: relu

critic_network:
  pre_torso:
    _target_: mava.networks.torsos.MLPTorso
    layer_sizes: [128]
    use_layer_norm: False
    activation: relu
  post_torso:
    _target_: mava.networks.torsos.MLPTorso
    layer_sizes: [128]
    use_layer_norm: False
    activation: relu

q_network:
  pre_torso:
    _target_: mava.networks.torsos.MLPTorso
    layer_sizes: [128]
    use_layer_norm: False
    activation: relu
  post_torso:
    _target_: mava.networks.torsos.MLPTorso
    layer_sizes: [128]
    use_layer_norm: False
    activation: relu
