defaults:
  - logger: logger
  - arch: anakin
  - system: ppo/ff_mappo
  - network: mlp # [mlp, cnn]
  - env: rware # [cleaner, connector, vector-connector, gigastep, lbf, mabrax, matrax, rware, smax, mpe]
  - _self_

hydra:
  searchpath:
    - file://mava/configs
