defaults:
  - logger: logger
  - arch: anakin
  - system: sable/ff_sable
  - network: ff_retention
  - env: rware # [cleaner, connector, vector-connector, gigastep, lbf, matrax, rware, smax, mpe]
  - _self_

hydra:
  searchpath:
    - file://mava/configs
