defaults:
  - logger: logger
  - arch: sebulba
  - system: sable/ff_sable
  - network: ff_retention
  - env: rware_gym  # [rware_gym, lbf_gym, smaclite_gym]
  - _self_

hydra:
  searchpath:
    - file://mava/configs
