defaults:
  - logger: logger
  - arch: anakin
  - system: mat/mat
  - network: transformer
  - env: rware # [cleaner, connector, vector-connector, gigastep, lbf, mabrax, matrax, rware, smax, mpe]
  - _self_

hydra:
  searchpath:
    - file://mava/configs
