defaults:
  - logger: logger
  - arch: sebulba
  - system: ppo/rec_mappo
  - network: rnn  # [mlp, continuous_mlp, cnn]
  - env: rware_gym  # [rware_gym, lbf_gym, smaclite_gym]
  - _self_

hydra:
  searchpath:
    - file://mava/configs
