defaults:
  - logger: logger
  - arch: anakin
  - system: ppo/rec_happo
  - network: rnn
  - env: rware # [cleaner, connector, vector-connector, gigastep, lbf, matrax, rware, smax, mpe]
  - _self_

hydra:
  searchpath:
    - file://mava/configs
