# ---Environment Configs---
defaults:
  - _self_
  - scenario: clean-5x5x5a # [clean-5x5x5a, clean-10x10x10a, clean-15x15x15a, clean-20x20x20a, clean-30x30x30a]
# Further environment config details in "clean-5x5x3a" file.

env_name: Cleaner # Used for logging purposes.

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return

# Whether the environment observations encode implicit agent IDs. If True, the AgentID wrapper is not used.
# This should not be changed.
implicit_agent_id: True
# Whether or not to log the winrate of this environment. This should not be changed as not all
# environments have a winrate metric.
log_win_rate: True

kwargs:
  {}  # time limit set in scenario
